import { LinksFunction } from "@remix-run/node";
import Lion from "~/assets/lion.png";
import '../styles/index.css';
import { Header } from "~/components/Header/Header";
import { Footer } from "~/components/Footer/Footer";

export default function Impressum() {
  return (
    <>
    <Header />

    <main className="container pvc">
  
  <h1><strong>Datenschutzerklärung</strong></h1>
          <p><b>Verantwortlicher für die Datenverarbeitung ist:</b><br /> Ömer OK<br /> Fössestr. 99a<br /> 30453 Hannover<br /> Deutschland<br /> joeloffice@renting24.de</p>
          <p>Wir freuen uns über Ihr Interesse an unserer Webseite. Der Schutz Ihrer Privatsphäre ist für uns sehr wichtig. Nachstehend informieren wir Sie ausführlich über den Umgang mit Ihren Daten.<br /></p>
          <h2>1. Zugriffsdaten und Hosting </h2>
           <p>Sie können unsere Webseiten besuchen, ohne Angaben zu Ihrer Person zu machen. Bei jedem Aufruf einer Webseite speichert der Webserver lediglich automatisch ein sogenanntes Server-Logfile, das z.B. den Namen der angeforderten Datei, Ihre IP-Adresse, Datum und Uhrzeit des Abrufs, übertragene Datenmenge und den anfragenden Provider (Zugriffsdaten) enthält und den Abruf dokumentiert. Diese Zugriffsdaten werden ausschließlich zum Zwecke der Sicherstellung eines störungsfreien Betriebs der Seite sowie der Verbesserung unseres Angebots ausgewertet. Dies dient der Wahrung unserer im Rahmen einer Interessensabwägung überwiegenden berechtigten Interessen an einer korrekten Darstellung unseres Angebots gemäß Art. 6 Abs. 1 S. 1 lit. f DSGVO. 
           Alle Zugriffsdaten werden spätestens sieben Tage nach Ende Ihres Seitenbesuchs gelöscht. 
          </p><h3> Hosting </h3>
          <p>Die Dienste zum Hosting und zur Darstellung der Webseite werden teilweise durch unsere Dienstleister im Rahmen einer Verarbeitung in unserem Auftrag erbracht. Soweit im Rahmen der vorliegenden Datenschutzerklärung nichts anderes erläutert wird, werden alle Zugriffsdaten sowie alle Daten, die in dafür vorgesehenen Formularen auf dieser Webseite erhoben werden, auf ihren Servern verarbeitet. Bei Fragen zu unseren Dienstleistern und der Grundlage unserer Zusammenarbeit mit ihnen wenden Sie sich bitte an die in dieser Datenschutzerklärung beschriebenen Kontaktmöglichkeit.</p>
           <p>Eine Datenübermittlung kann an ein Drittland/ an Drittländer, für die die Europäische Kommission kein angemessenes Datenschutzniveau festgestellt hat, aufgrund des Einsatzes von zusätzlichen Funktionen unseres Dienstleisters erfolgen. Ein angemessenes Datenschutzniveau wird dabei durch den Abschluss von Standardvertragsklauseln der Europäischen Kommission gewährleistet.</p> 
          <p>Unsere Dienstleister sitzen und/oder verwenden Server in folgenden Ländern, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat: USA</p>
           <p>Es liegt ein Beschluss der Europäischen Kommission über ein angemessenes Datenschutzniveau für die USA als Grundlage für eine Drittlandsübermittlung vor, soweit der jeweilige Dienstleister zertifiziert ist. Bis zur Zertifizierung durch unsere Dienstleister stützt sich die Datenübermittlung weiterhin auf diese Grundlage: Standarddatenschutzklauseln der Europäischen Kommission.</p> 
          <h2>2. Datenverarbeitung zur Kontaktaufnahme und Kundenkommunikation </h2>
          <p>Wir erheben personenbezogene Daten, wenn Sie uns diese bei einer Kontaktaufnahme mit uns (z.B. per Kontaktformular oder E-Mail) freiwillig mitteilen. Pflichtfelder werden als solche gekennzeichnet, da wir in diesen Fällen die Daten zwingend zur Bearbeitung Ihrer Kontaktaufnahme benötigen und sie ohne deren Angabe die Kontaktaufnahme nicht versenden können. Welche Daten erhoben werden, ist aus den jeweiligen Eingabeformularen ersichtlich. Wir verwenden die von ihnen mitgeteilten Daten zur Bearbeitung Ihrer Anfragen gemäß Art. 6 Abs. 1 S. 1 lit. b DSGVO. </p> <p>Nach vollständiger Abwicklung Ihrer Kundenanfrage werden Ihre Daten für die weitere Verarbeitung eingeschränkt und nach Ablauf der steuer- und handelsrechtlichen Aufbewahrungsfristen gemäß Art. 6 Abs. 1 S. 1 lit. c DSGVO gelöscht, sofern Sie nicht ausdrücklich in eine weitere Nutzung Ihrer Daten gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO eingewilligt haben oder wir uns eine darüber hinausgehende Datenverwendung vorbehalten, die gesetzlich erlaubt ist und über die wir Sie in dieser Erklärung informieren. </p>
          <h4> Live-Chat-Tool WhatsApp </h4>
          
          <p>Zum Zwecke der Kundenkommunikation verwenden wir das Live-Chat-Tool der WhatsApp Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland („WhatsApp“). Dies dient der Wahrung unserer im Rahmen einer Interessenabwägung überwiegenden berechtigten Interessen an einer effektiven und verbesserten Kundenkommunikation gemäß Art. 6 Abs. 1 S. 1 lit. f DSGVO. WhatsApp ist in unserem Auftrag für uns tätig. Die die von uns auf unserem mobilen Endgerät gespeicherten Telefonnummern werden automatisch auf Servern von Meta Unternehmen mit ihrem Hauptsitz in 1601 Willow Road, Menlo Park, California 94025, USA verarbeitet. Dabei werden ausschließlich Telefonnummern von Kunden gespeichert, die uns zuvor über WhatsApp kontaktiert und die Nutzungs- und Datenschutzbedingungen von WhatsApp daher bereits akzeptiert haben.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in folgenden Ländern, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat: USA, Israel, Vereinigtes Königreich.</p> <p>Es liegt ein Beschluss der Europäischen Kommission über ein angemessenes Datenschutzniveau für die USA als Grundlage für eine Drittlandsübermittlung vor, soweit der jeweilige Dienstleister zertifiziert ist. Eine Zertifizierung liegt vor.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in diesen Ländern: Singapur. Für diese Länder liegt kein Angemessenheitsbeschluss der Europäischen Kommission vor. Unsere Zusammenarbeit mit Ihnen stützt sich auf diese Garantien:  Standarddatenschutzklauseln der Europäischen Kommission.</p>
          <h2>3. Werbung per E-Mail</h2>
          <h3>3.1 E-Mail-Newsletter mit Anmeldung, Newsletter-Tracking mit gesonderter Einwilligung </h3>
          <p>Wenn Sie sich zu unserem Newsletter anmelden, verwenden wir die hierfür erforderlichen oder gesondert von Ihnen mitgeteilten Daten, um Ihnen regelmäßig unseren E-Mail-Newsletter aufgrund Ihrer Einwilligung gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO zuzusenden.<br /></p>
          <p>Die Abmeldung vom Newsletter ist jederzeit möglich und kann entweder durch eine Nachricht an die unten beschriebene Kontaktmöglichkeit oder über einen dafür vorgesehenen Link im Newsletter erfolgen.
           Nach Abmeldung löschen wir Ihre E-Mail-Adresse aus der Empfängerliste, soweit Sie nicht ausdrücklich in eine weitere Nutzung Ihrer Daten gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO eingewilligt haben oder wir uns eine darüber hinausgehende Datenverwendung vorbehalten, die gesetzlich erlaubt ist und über die wir Sie in dieser Erklärung informieren. 
          </p> <p>Wenn Sie uns zusätzlich Ihre Einwilligung gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO zur Analyse unserer Newsletter erteilt haben, analysieren wir auch Ihren Umgang mit unserem Newsletter durch Messung, Speicherung und Auswertung von Öffnungsraten und der Klickraten zum Zweck der Gestaltung künftiger Newsletterkampagnen („Newsletter-Tracking“). </p> <p>Für diese Auswertung beinhalten die versendeten E-Mails Ein-Pixel-Technologien (z.B. sog. Web-Beacons, Tracking-Pixel), die auf unserer Website gespeichert sind. Für die Auswertungen verknüpfen wir insbesondere die folgenden „Newsletterdaten“ </p> <ul> <li>die Seite, von der aus die Seite angefordert wurde (sog. Referrer-URL), </li> <li>das Datum und die Uhrzeit des Aufrufs, </li> <li>die Beschreibung des Typs des verwendeten Webbrowsers, </li> <li>die IP-Adresse des anfragenden Rechners, </li> <li>die E-Mail-Adresse, </li> <li>das Datum und die Uhrzeit der Anmeldung und Bestätigung </li> </ul> <p>und die Ein-Pixel-Technologien mit Ihrer E-Mail-Adresse oder Ihrer IP-Adresse und ggf. einer individuellen ID. Auch im Newsletter enthaltene Links können diese ID enthalten. </p> <p>Die Abmeldung vom Newsletter-Tracking ist jederzeit möglich und kann entweder durch eine Nachricht an die beschriebene Kontaktmöglichkeit oder über einen dafür vorgesehenen Link im Newsletter erfolgen. </p> <p>Die Informationen werden solange gespeichert, wie Sie den Newsletter abonniert haben. </p> 
          <h3>3.2 Newsletterversand </h3>
           <p>Der Newsletter und das oben dargestellte Newsletter-Tracking wird gegebenenfalls auch durch unsere Dienstleister im Rahmen einer Verarbeitung in unserem Auftrag versendet. Bei Fragen zu unseren Dienstleistern und der Grundlage unserer Zusammenarbeit mit ihnen wenden Sie sich bitte an die in dieser Datenschutzerklärung beschriebenen Kontaktmöglichkeit.</p> 
          <p>Unsere Dienstleister sitzen und/oder verwenden Server in folgenden Ländern, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat: USA</p>
           <p>Es liegt ein Beschluss der Europäischen Kommission über ein angemessenes Datenschutzniveau für die USA als Grundlage für eine Drittlandsübermittlung vor, soweit der jeweilige Dienstleister zertifiziert ist. Bis zur Zertifizierung durch unsere Dienstleister stützt sich die Datenübermittlung weiterhin auf diese Grundlage: Standarddatenschutzklauseln der Europäischen Kommission.</p> 
          <h2>4. Cookies und weitere Technologien</h2>
          <h3>4.1 Allgemeine Informationen</h3>
           <p>Um den Besuch unserer Webseite attraktiv zu gestalten und die Nutzung bestimmter Funktionen zu ermöglichen, verwenden wir auf verschiedenen Seiten Technologien einschließlich sogenannter Cookies. Cookies sind kleine Textdateien, die automatisch auf Ihrem Endgerät gespeichert werden. Einige der von uns verwendeten Cookies werden nach Ende der Browser-Sitzung, also nach Schließen Ihres Browsers, wieder gelöscht (sog. Sitzungs-Cookies). Andere Cookies verbleiben auf Ihrem Endgerät und ermöglichen uns, Ihren Browser beim nächsten Besuch wiederzuerkennen (persistente Cookies).</p> <p><strong>Schutz der Privatsphäre bei Endgeräten</strong><br /> Bei Nutzung unseres Online-Angebots setzen wir unbedingt notwendige Technologien ein, um den ausdrücklich gewünschten Telemediendienst zur Verfügung stellen zu können. Die Speicherung von Informationen in Ihrem Endgerät oder der Zugriff auf Informationen, die bereits in Ihrem Endgerät gespeichert sind, bedürfen insoweit keiner Einwilligung.</p>  
           <p>Bei nicht unbedingt erforderlichen Funktionen bedarf die Speicherung von Informationen in Ihrem Endgerät oder der Zugriff auf Informationen, die bereits in Ihrem Endgerät gespeichert sind, Ihrer Einwilligung. Wir weisen Sie darauf hin, dass bei Nichterteilung der Einwilligung ggf. Teile der Webseite nicht uneingeschränkt nutzbar sein können. Ihre etwaig erteilten Einwilligungen bleiben solange bestehen, bis Sie die jeweiligen Einstellungen in Ihrem Endgerät anpassen oder zurücksetzen.</p> 
           <p><strong>Etwaig nachgelagerte Datenverarbeitung durch Cookies und weitere Technologien</strong><br /> <br /> Wir verwenden solche Technologien, die für die Nutzung bestimmter Funktionen unserer Webseite (z. B. Präferenzeinstellungen der Webseite) zwingend erforderlich sind. Durch diese Technologien werden IP-Adresse, Zeitpunkt des Besuchs, Geräte- und Browser-Informationen sowie Informationen zu Ihrer Nutzung unserer Webseite (z.B. Informationen zu Ihren Präferenzen) erhoben und verarbeitet. Dies dient im Rahmen einer Interessensabwägung überwiegenden berechtigten Interessen an einer optimierten Darstellung unseres Angebots gemäß Art. 6 Abs. 1 S. 1 lit. f DSGVO. </p> 
           <p>Zudem verwenden wir Technologien zur Erfüllung der rechtlichen Verpflichtungen, denen wir unterliegen (z.B. um Einwilligungen in die Verarbeitung Ihrer personenbezogenen Daten nachweisen zu können) sowie zu Webanalyse und Online-Marketing. Weitere Informationen hierzu einschließlich der jeweiligen Rechtsgrundlage für die Datenverarbeitung finden Sie in den nachfolgenden Abschnitten dieser Datenschutzerklärung.</p> 
          <p>Gegebenenfalls verwenden wir darüber hinaus Technologien, die in dieser Datenschutzerklärung nicht einzeln aufgelistet sind. Nähere Informationen zu diesen Technologien einschließlich der jeweiligen Rechtsgrundlage für die Datenverarbeitung finden Sie auf der Usercentrics Plattform.</p>
          <p>Diese erreichen Sie unter diesem Link: https://renting24.de/datenschutz.
          </p><p>Die Cookie-Einstellungen für Ihren Browser finden Sie unter den folgenden Links: <a href="https://support.microsoft.com/de-de/help/4027947/microsoft-edge-delete-cookies" target="_blank">Microsoft Edge™</a> / <a href="https://support.apple.com/de-de/guide/safari/sfri11471/12.0/mac/10.14" target="_blank">Safari™</a> / <a href="https://support.google.com/chrome/answer/95647?hl=de&hlrm=en" target="_blank">Chrome™</a> / <a href="https://support.mozilla.org/de/products/firefox/protect-your-privacy/cookies" target="_blank">Firefox™</a> / <a href="https://help.opera.com/de/latest/web-preferences/#cookies" target="_blank">Opera™</a>
          </p> <p>Soweit Sie in die Verwendung der Technologien gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO eingewilligt haben, können Sie Ihre Einwilligung jederzeit widerrufen durch eine Nachricht an die in der Datenschutzerklärung beschriebenen Kontaktmöglichkeit. 
          Alternativ können Sie auch folgenden Link aufrufen: https://renting24.de/datenschutz. Bei der Nichtannahme von Cookies kann die Funktionalität unserer Webseite eingeschränkt sein.
          </p><h3>4.2 Einsatz von Usercentrics Consent Management Plattform zur Verwaltung von Einwilligungen</h3>
          <p>Auf unserer Webseite setzen wir die <a href="https://usercentrics.com/de/" target="_blank">Usercentrics Consent Management Plattform</a> („Usercentrics“) ein, um Sie über die Cookies und die anderen Technologien zu informieren, die wir auf unserer Webseite verwenden, sowie Ihre gegebenenfalls gesetzlich erforderliche Einwilligung in die Verarbeitung Ihrer personenbezogenen Daten durch diese Technologien einzuholen, zu verwalten und zu dokumentieren. Dies ist gemäß Art. 6 Abs. 1 S. 1 lit. c DSGVO zur Erfüllung unserer rechtlichen Verpflichtung gemäß Art. 7 Abs. 1 DSGVO erforderlich, Ihre Einwilligung in die Verarbeitung Ihrer personenbezogenen Daten nachweisen zu können, der wir unterliegen. Usercentrics ist ein Angebot der Usercentrics GmbH, Sendlinger Straße 7, 80331 München, Deutschland die in unserem Auftrag Ihre Daten verarbeitet. Bei Besuch unserer Webseite speichert der Webserver von Usersentrics ein sogenanntes Server-Logfile, das auch Ihre anonymisierte IP-Adresse, Datum und Uhrzeit des Besuchs, Geräte- und Browser-Informationen sowie Informationen zu Ihrem Einwilligungsverhalten enthält. Ihre Daten werden nach drei Jahren gelöscht, sofern Sie nicht ausdrücklich in eine weitere Nutzung Ihrer Daten gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO eingewilligt haben oder wir uns eine darüber hinausgehende Datenverwendung vorbehalten, die gesetzlich erlaubt ist und über die wir Sie in dieser Erklärung informieren.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in folgenden Ländern, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat: USA.<br /> <br /> Es liegt ein Beschluss der Europäischen Kommission über ein angemessenes Datenschutzniveau für die USA als Grundlage für eine Drittlandsübermittlung vor, soweit der jeweilige Dienstleister zertifiziert ist. Eine Zertifizierung liegt vor.</p>
          <h2>5. Einsatz von Cookies und anderen Technologien </h2>
           <p>Soweit Sie hierzu Ihre Einwilligung nach Art. 6 Abs. 1 S. 1 lit. a DSGVO erteilt haben, verwenden wir auf unserer Webseite die nachfolgenden Cookies und andere Technologien von Drittanbietern. Nach Zweckfortfall und Ende des Einsatzes der jeweiligen Technologie durch uns werden die in diesem Zusammenhang erhobenen Daten gelöscht. Sie können Ihre Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Weitere Informationen zu Ihren Widerrufsmöglichkeiten finden Sie in dem Abschnitt "Cookies und weitere Technologien". Weitere Informationen einschließlich der Grundlage unserer Zusammenarbeit mit den einzelnen Anbietern finden Sie bei den einzelnen Technologien. Bei Fragen zu den Anbietern und der Grundlage unserer Zusammenarbeit mit ihnen wenden Sie sich bitte an die in dieser Datenschutzerklärung beschriebenen Kontaktmöglichkeit.</p> 
          <h3>5.1 Einsatz von Google-Diensten </h3>
          <p>Wir verwenden die nachfolgend dargestellten Technologien der Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Irland („Google“). Die durch die Google Technologien automatisch erhobenen Informationen über Ihre Nutzung unserer Webseite werden in der Regel an einen Server der Google LLC, 1600 Amphitheatre Parkway Mountain View, CA 94043, USA übertragen und dort gespeichert. Soweit bei den einzelnen Technologien nichts Abweichendes angeben ist, erfolgt die Datenverarbeitung auf Grundlage einer für die jeweilige Technologie geschlossenen Vereinbarung zwischen gemeinsam Verantwortlichen gemäß Art. 26 DSGVO. Weitergehende Informationen über die Datenverarbeitung durch Google finden Sie in den <a href="https://policies.google.com/privacy?hl=de" target="_blank">Datenschutzhinweisen von Google</a>.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in Ländern außerhalb der EU und des EWR, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in Ländern außerhalb der EU und des EWR. Für diese Länder liegt kein Angemessenheitsbeschluss der Europäischen Kommission vor. Unsere Zusammenarbeit mit ihnen stützt sich auf Standarddatenschutzklauseln der Europäischen Kommission. </p>
          <h4> Google Analytics</h4>
           <p>Zum Zweck der Webseitenanalyse werden mit Google Analytics Daten (IP-Adresse, Zeitpunkt des Besuchs, Geräte- und Browser-Informationen sowie Informationen zu Ihrer Nutzung unserer Webseite) automatisch erhoben und gespeichert, aus denen unter Verwendung von Pseudonymen Nutzungsprofile erstellt werden. Hierzu können Cookies eingesetzt werden. Wenn Sie unsere Webseite aus der EU besuchen, wird Ihre IP-Adresse auf einem Server mit Stand in der EU zur Ableitung von Standortdaten gespeichert und danach sofort gelöscht, bevor der Traffic zur Verarbeitung auf weiteren Servern von Google weitergeleitet wird. Die Datenverarbeitung erfolgt auf Grundlage einer Vereinbarung über die Auftragsverarbeitung durch Google.</p> 
           <p>Zum Zwecke der optimierten Vermarktung unserer Webseite haben wir die<strong> Datenfreigabeeinstellungen für "Google-Produkte und -Dienste" </strong>aktiviert. So kann Google auf die von Google Analytics erhobenen und verarbeiteten Daten zugreifen und anschließend zur Verbesserung der Google-Dienste verwenden. Die Datenfreigabe an Google im Rahmen dieser Datenfreigabeeinstellungen erfolgt auf Grundlage einer zusätzlichen Vereinbarung zwischen Verantwortlichen. Wir haben keinen Einfluss auf die anschließende Datenverarbeitung durch Google.</p> 
           <p>Zur Erstellung und Durchführung von Tests verwenden wir zudem die Erweiterungsfunktion von Google Analytics <strong>Google Optimize</strong>.</p> 
          <p>Zum Zwecke der optimierten Vermarktung unserer Webseite nutzen wir die sog. <strong>User-ID-Funktion</strong>. Mithilfe dieser Funktion können wir Ihren Interaktionsdaten einer oder mehreren Sitzungen auf unseren Online-Auftritten eine eindeutige, permanente ID zuweisen und somit Ihr Nutzerverhalten geräte- und sitzungsüberübergreifend analysieren.</p> 
           <p>Zur Webanalyse wird durch die Erweiterungsfunktion von Google Analytics <strong>Google Signals</strong> ein sog. „Cross-Device Tracking“ ermöglicht. Soweit Ihre internetfähigen Geräte mit Ihrem Google-Konto verknüpft sind und Sie die Einstellung „personalisierte Werbung“ in Ihrem Google Konto aktiviert haben, kann Google Berichte über Ihr Nutzungsverhalten (insb. die geräteübergreifenden Nutzerzahlen) erstellen, auch wenn Sie Ihr Endgerät wechseln. Eine Verarbeitung von personenbezogenen Daten durch uns findet insoweit nicht statt, wir erhalten lediglich auf Basis von Google Signals erstellte Statistiken.</p> 
          <h4> Google Ads </h4>
           <p>Zu Werbezwecken in den Google Suchergebnissen sowie auf den Webseiten Dritter wird bei Besuch unserer Webseite das sog. Google <strong>Remarketing </strong>Cookie gesetzt, das automatisch durch die Erhebung und Verarbeitung von Daten (IP-Adresse, Zeitpunkt des Besuchs, Geräte- und Browser-Informationen sowie Informationen zu Ihrer Nutzung unserer Webseite) und mittels einer pseudonymen CookieID und auf Grundlage der von Ihnen besuchten Seiten eine interessenbasierte Werbung ermöglicht. Eine darüber hinausgehende Datenverarbeitung findet nur statt, sofern Sie die Einstellung „personalisierte Werbung“ in Ihrem Google Konto aktiviert haben. Sind sie in diesem Fall während des Besuchs unserer Webseite bei Google eingeloggt, verwendet Google Ihre Daten zusammen mit Google Analytics-Daten, um Zielgruppenlisten für geräteübergreifendes Remarketing zu erstellen und zu definieren.</p> 
           <p>Zur Webseitenanalyse und Ereignisverfolgung messen wir über das Google Ads <strong>Conversion Tracking</strong> Ihr nachfolgendes Nutzungsverhalten, wenn Sie über eine Werbeanzeige von Google Ads auf unsere Website gelangt sind. Hierzu können Cookies eingesetzt und Daten (IP-Adresse, Zeitpunkt des Besuchs, Geräte- und Browser-Informationen sowie Informationen zu Ihrer Nutzung unserer Webseite anhand von uns vorgegebenen Ereignissen wie z.B. Besuch einer Webseite oder Newsletteranmeldung) erfasst werden, aus denen unter Verwendung von Pseudonymen Nutzungsprofile erstellt werden.</p> 
          <h4> Google Maps </h4>
           <p>Zur visuellen Darstellung von geographischen Informationen werden durch Google Maps Daten über Ihre Nutzung der Maps-Funktionen, insbesondere die IP-Adresse sowie Standortdaten, erhoben, an Google übermittelt und anschließend von Google verarbeitet. Wir haben keinen Einfluss auf diese anschließende Datenverarbeitung.</p> 
          <h4> Google Fonts </h4>
           <p>Zur einheitlichen Darstellung der Inhalte auf unserer Webseite werden durch den Script Code „Google Fonts“ Daten (IP-Adresse, Zeitpunkt des Besuchs, Geräte- und Browser-Informationen) erhoben, an Google übermittelt und anschließend von Google verarbeitet. Wir haben keinen Einfluss auf diese anschließende Datenverarbeitung.</p> 
          <h4> Google Tag Manager  </h4>
           <p>Durch den Google Tag Manager können wir verschiedene Codes und Dienste auf unserer Webseite verwalten. Bei der Implementierung der einzelnen Tags verarbeitet Google unter Umständen auch personenbezogene Daten (z.B. IP Adresse, Online-Kennungen (u.a. Cookies)). Die Datenverarbeitung erfolgt auf Grundlage einer Vereinbarung über die Auftragsverarbeitung durch Google. </p> <p>Durch den Einsatz des Google Tag Managers lässt sich eine Einbindung verschiedener Dienste/Technologien erreichen. <br /> Sofern Sie den Einsatz einzelner Trackingdienste nicht wünschen und diese daher deaktiviert haben, bleibt die Deaktivierung für alle betroffenen Tracking-Tags bestehen, die durch den Google Tag Manager eingebunden werden. </p> 
          <h4> YouTube Video Plugin </h4>
           <p>Zur Einbindung von Inhalten Dritter werden über das YouTube Video Plugin in dem von uns verwendeten erweiterten Datenschutzmodus Daten (IP-Adresse, Zeitpunkt des Besuchs, Geräte- und Browser-Informationen) erhoben, an Google übermittelt und anschließend von Google verarbeitet, nur wenn Sie ein Video abspielen.</p> 
          <h3>5.2 Einsatz von Facebook-Diensten</h3>
          <h4> Einsatz von Facebook Pixel</h4>
          <p>Wir verwenden das Facebook Pixel im Rahmen der nachfolgend dargestellten Technologien der <a href="http://de-de.facebook.com/facebookdublin/" target="_blank">Meta Platforms Ireland Ltd.</a>, Block J, Serpentine Avenue, Dublin 4, Irland („Facebook (by Meta)“ bzw. “Meta Platforms Ireland“). Mit dem Facebook Pixel werden Daten (IP-Adresse, Zeitpunkt des Besuchs, Geräte- und Browser-Informationen sowie Informationen zu Ihrer Nutzung unserer Webseite anhand von uns vorgegebenen Ereignissen wie z.B. Besuch einer Webseite oder Newsletteranmeldung) automatisch erhoben und gespeichert, aus denen unter Verwendung von Pseudonymen Nutzungsprofile erstellt werden. 
          Im Rahmen des sog. erweiterten Datenabgleichs werden darüber hinaus Informationen zu Abgleichzwecken gehasht erhoben und gespeichert, mit denen Einzelpersonen identifiziert werden können (z.B. Namen, E-Mail-Adressen und Telefonnummern).
          Hierzu wird bei Besuch unserer Webseite durch das Facebook Pixel automatisch ein Cookie gesetzt, das automatisch mittels einer pseudonymen CookieID eine Wiedererkennung Ihres Browsers beim Besuch anderer Webseiten ermöglicht. Facebook (by Meta) wird diese Informationen mit weiteren Daten aus Ihrem Facebook-Konto zusammenführen und benutzen, um Reports über die Webseitenaktivitäten zusammenzustellen und um weitere mit der Webseitennutzung verbundene Dienstleistungen, insbesondere personalisierte und gruppenbasierte Werbung zu erbringen.<br /> Die durch die Facebook (by Meta) Technologien automatisch erhobenen Informationen über Ihre Nutzung unserer Webseite werden in der Regel an einen Server der Meta Platforms, Inc., 1601 Willow Road, Menlo Park, California 94025, USA übertragen und dort gespeichert. Weitergehende Informationen über die Datenverarbeitung durch Facebook finden Sie in den <a href="https://de-de.facebook.com/privacy/policy/?entry_point=data_policy_redirect&entry=0" target="_blank">Datenschutzhinweisen von Facebook (by Meta)</a>. Unsere Dienstleister sitzen und/oder verwenden Server in folgenden Ländern, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat: USA, Kanada, Japan, Südkorea, Neuseeland, Vereinigtes Königreich, Argentinien. Es liegt ein Beschluss der Europäischen Kommission über ein angemessenes Datenschutzniveau für die USA als Grundlage für eine Drittlandsübermittlung vor, soweit der jeweilige Dienstleister zertifiziert ist. Eine Zertifizierung liegt vor. Unsere Dienstleister sitzen und/oder verwenden Server in diesen Ländern: Australien, Hongkong, Indien, Indonesien, Malaysia, Singapur, Thailand, Taiwan, Brasilien, Mexiko. <br /> Für diese Länder liegt kein Angemessenheitsbeschluss der Europäischen Kommission vor. Unsere Zusammenarbeit mit Ihnen stützt sich auf diese Garantien:  Standarddatenschutzklauseln der Europäischen Kommission.
          </p><h4> Facebook Analysen </h4>
           <p>Im Rahmen der Facebook Business-Tools werden aus den mit dem Facebook Pixel erhobenen Daten über Ihre Nutzung unserer Webseite Statistiken über Besucheraktivitäten auf unserer Webseite erstellt. Die Datenverarbeitung erfolgt auf Grundlage einer Vereinbarung über die Auftragsverarbeitung durch Facebook (by Meta). Ihre Analyse dient der optimalen Darstellung und Vermarktung unserer Webseite. </p> 
          <h4> Facebook Ads (Werbeanzeigenmanager) </h4>
           <p>Über Facebook Ads werben wir für diese Website auf Facebook (by Meta) sowie auf anderen Plattformen. Wir bestimmen die Parameter der jeweiligen Werbekampagne. Für die genaue Umsetzung, insbesondere die Entscheidung über die Platzierung der Anzeigen bei einzelnen Nutzern, ist Facebook (by Meta) verantwortlich. Soweit bei den einzelnen Technologien nichts Abweichendes angeben ist, erfolgt die Datenverarbeitung auf Grundlage einer Vereinbarung zwischen gemeinsam Verantwortlichen gemäß Art. 26 DSGVO. Die gemeinsame Verantwortlichkeit beschränkt sich auf die Erhebung der Daten und ihre Übermittlung an Meta Platforms Ireland. Die anschließende Datenverarbeitung durch Meta Platforms Ireland ist hiervon nicht erfasst.</p> 
           <p>Auf Grundlage der über Facebook Pixel erstellten Statistiken über Besucheraktivitäten auf unserer Webseite betreiben wir über Facebook <strong>Custom Audience</strong> gruppenbasierte Werbung auf Facebook (by Meta), indem wir die Merkmale der jeweiligen Zielgruppe bestimmen. 
          ​​​​​​​Im Rahmen des zur Bestimmung der jeweiligen Zielgruppe stattfindenden erweiterten Datenabgleichs (s.o.) handelt Facebook als unser Auftragsverarbeiter.
          </p><p>Auf Grundlage der vom Facebook Pixel gesetzten pseudonymen Cookie-ID und der erhobenen Daten über Ihr Nutzungsverhaltens auf unserer Webseite betreiben wir über Facebook Pixel <strong>Remarketing</strong> personalisierte Werbung.</p> 
           <p>Über Facebook Pixel <strong>Conversions </strong>messen wir zur Webanalyse und Ereignisverfolgung Ihr nachfolgendes Nutzungsverhalten, wenn Sie über eine Werbeanzeige von Facebook Ads unsere Website gelangt sind. Die Datenverarbeitung erfolgt auf Grundlage einer Vereinbarung über die Auftragsverarbeitung durch Facebook (by Meta).</p> 
          <h2>6. Social Media </h2>
          <h3>6.1 Social Buttons von Facebook (by Meta), Instagram (by Meta), Whatsapp</h3>
           <p>Auf unserer Webseite werden Social Buttons von sozialen Netzwerken verwendet. Diese sind lediglich als HTML-Links in die Seite eingebunden, so dass beim Aufruf unserer Webseite noch keine Verbindung mit den Servern des jeweiligen Anbieters hergestellt wird. Klicken Sie auf einen der Buttons, öffnet sich die Webseite des jeweiligen sozialen Netzwerks in einem neuen Fenster Ihres Browsers Dort können Sie z.B. den Like- oder Share-Button betätigen.</p> 
          <h3>6.2 Unsere Onlinepräsenz auf Facebook (by Meta), Instagram (by Meta), Youtube</h3>
          <p>Soweit Sie hierzu Ihre Einwilligung nach Art. 6 Abs. 1 S. 1 lit. a DSGVO gegenüber dem jeweiligen Social Media Betreiber erteilt haben, werden bei Besuch unserer Onlinepräsenzen auf den in der oben genannten sozialen Medien Ihre Daten für Marktforschungs- und Werbezwecke automatisch erhoben und gespeichert, aus denen unter Verwendung von Pseudonymen Nutzungsprofile erstellt werden. Diese können verwendet werden, um z.B. Werbeanzeigen innerhalb und außerhalb der Plattformen zu schalten, die mutmaßlich Ihren Interessen entsprechen. Hierzu werden im Regelfall Cookies eingesetzt. Die detaillierten Informationen zur Verarbeitung und Nutzung der Daten durch den jeweiligen Social Media Betreiber sowie eine Kontaktmöglichkeit und Ihre diesbezüglichen Rechte und Einstellungsmöglichkeiten zum Schutz Ihrer Privatsphäre, entnehmen Sie bitte den unten verlinkten Datenschutzhinweisen der Anbieter. Sollten Sie diesbezüglich dennoch Hilfe benötigen, können Sie sich an uns wenden.</p>
          <p><a href="http://www.facebook.com/about/privacy/"><strong>Facebook </strong>(by Meta)</a> ist ein Angebot der Meta Platforms Ireland Ltd., Block J, Serpentine Avenue, Dublin 4, Irland („Meta Platforms Ireland“). Die durch Meta Platforms Ireland automatisch erhobenen Informationen über Ihre Nutzung unserer Online-Präsenz auf Facebook (by Meta) werden in der Regel an einen Server der Meta Platforms, Inc., 1601 Willow Road, Menlo Park, California 94025, USA übertragen und dort gespeichert. Die Datenverarbeitung im Rahmen des Besuchs einer Facebook (by Meta) Fanpage erfolgt auf Grundlage einer Vereinbarung zwischen gemeinsam Verantwortlichen gemäß Art. 26 DSGVO. Weitere Informationen (Informationen zu Insights-Daten) finden Sie <a href="https://www.facebook.com/legal/terms/information_about_page_insights_data" target="_blank">hier</a>.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in folgenden Ländern, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat: USA, Kanada, Japan, Südkorea, Neuseeland, Vereinigtes Königreich, Argentinien.</p> <p>Es liegt ein Beschluss der Europäischen Kommission über ein angemessenes Datenschutzniveau für die USA als Grundlage für eine Drittlandsübermittlung vor, soweit der jeweilige Dienstleister zertifiziert ist. Eine Zertifizierung liegt vor.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in diesen Ländern: Australien, Hongkong, Indien, Indonesien, Malaysia, Singapur, Thailand, Taiwan, Brasilien, Mexiko.<br /> Für diese Länder liegt kein Angemessenheitsbeschluss der Europäischen Kommission vor. Unsere Zusammenarbeit mit Ihnen stützt sich auf diese Garantien:  Standarddatenschutzklauseln der Europäischen Kommission.</p>
          <p><a href="http://help.instagram.com/519522125107875" target="_blank"><strong>Instagram</strong> (by Meta)</a> ist ein Angebot der Meta Platforms Ireland Ltd., Block J, Serpentine Avenue, Dublin 4, Irland („Meta Platforms Ireland“) Die durch Meta Platforms Ireland automatisch erhobenen Informationen über Ihre Nutzung unserer Online-Präsenz auf Instagram werden in der Regel an einen Server der Meta Platforms, Inc., 1601 Willow Road, Menlo Park, CA 94025, USA, Menlo Park, California 94025, USA übertragen und dort gespeichert. Die Datenverarbeitung im Rahmen des Besuchs einer Instagram (by Meta) Fanpage erfolgt auf Grundlage einer Vereinbarung zwischen gemeinsam Verantwortlichen gemäß Art. 26 DSGVO. Weitere Informationen (Informationen zu Insights-Daten) finden Sie <a href="https://www.facebook.com/legal/terms/information_about_page_insights_data" target="_blank">hier</a>.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in folgenden Ländern, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat: USA, Kanada, Japan, Südkorea, Neuseeland, Vereinigtes Königreich, Argentinien.</p> <p>Es liegt ein Beschluss der Europäischen Kommission über ein angemessenes Datenschutzniveau für die USA als Grundlage für eine Drittlandsübermittlung vor, soweit der jeweilige Dienstleister zertifiziert ist. Eine Zertifizierung liegt vor.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in diesen Ländern: Australien, Hongkong, Indien, Indonesien, Malaysia, Singapur, Thailand, Taiwan, Brasilien, Mexiko.<br /> Für diese Länder liegt kein Angemessenheitsbeschluss der Europäischen Kommission vor. Unsere Zusammenarbeit mit Ihnen stützt sich auf diese Garantien: Standarddatenschutzklauseln der Europäischen Kommission.</p>
          <p><a href="https://policies.google.com/privacy?hl=de" target="_blank"><strong>YouTube</strong></a> ist ein Angebot der Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Irland („Google“). Die von Google automatisch erhobenen Informationen über Ihre Nutzung unserer Online-Präsenz auf YouTube werden in der Regel an einen Server der Google LLC, 1600 Amphitheatre Parkway Mountain View, CA 94043, USA übertragen und dort gespeichert.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in Ländern außerhalb der EU und des EWR, für die die Europäische Kommission durch Beschluss ein angemessenes Datenschutzniveau festgestellt hat.</p> <p>Unsere Dienstleister sitzen und/oder verwenden Server in Ländern außerhalb der EU und des EWR. Für diese Länder liegt kein Angemessenheitsbeschluss der Europäischen Kommission vor. Unsere Zusammenarbeit mit ihnen stützt sich auf Standarddatenschutzklauseln der Europäischen Kommission. </p>
          <h2>7. Kontaktmöglichkeiten und Ihre Rechte </h2>
          <h3>7.1 Ihre Rechte</h3>
           <p>Als Betroffener haben Sie folgende Rechte:</p> <ul> <li>gemäß Art. 15 DSGVO das Recht, in dem dort bezeichneten Umfang Auskunft über Ihre von uns verarbeiteten personenbezogenen Daten zu verlangen;</li> <li>gemäß Art. 16 DSGVO das Recht, unverzüglich die Berichtigung unrichtiger oder Vervollständigung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen;</li> <li>gemäß Art. 17 DSGVO das Recht, die Löschung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen, soweit nicht die weitere Verarbeitung <ul> <li>zur Ausübung des Rechts auf freie Meinungsäußerung und Information;</li> <li>zur Erfüllung einer rechtlichen Verpflichtung;</li> <li>aus Gründen des öffentlichen Interesses oder</li> <li>zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist;</li> </ul> </li> <li>gemäß Art. 18 DSGVO das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen, soweit <ul> <li>die Richtigkeit der Daten von Ihnen bestritten wird;</li> <li>die Verarbeitung unrechtmäßig ist, Sie aber deren Löschung ablehnen;</li> <li>wir die Daten nicht mehr benötigen, Sie diese jedoch zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigen oder</li> <li>Sie gemäß Art. 21 DSGVO Widerspruch gegen die Verarbeitung eingelegt haben;</li> </ul> </li> <li>gemäß Art. 20 DSGVO das Recht, Ihre personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten oder die Übermittlung an einen anderen Verantwortlichen zu verlangen;</li> <li>gemäß Art. 77 DSGVO das Recht, sich bei einer Aufsichtsbehörde zu beschweren. In der Regel können Sie sich hierfür an die Aufsichtsbehörde Ihres üblichen Aufenthaltsortes oder Arbeitsplatzes oder unseres Unternehmenssitzes wenden.</li> </ul> 
           <table border={1} style={{width: '100%'}}> <tbody> <tr> <td> <p><strong>Widerspruchsrecht</strong></p> <p>Soweit wir zur Wahrung unserer im Rahmen einer Interessensabwägung überwiegenden berechtigten Interessen personenbezogene Daten wie oben erläutert verarbeiten, können Sie dieser Verarbeitung mit Wirkung für die Zukunft widersprechen. Erfolgt die Verarbeitung zu Zwecken des Direktmarketings, können Sie dieses Recht jederzeit wie oben beschrieben ausüben. Soweit die Verarbeitung zu anderen Zwecken erfolgt, steht Ihnen ein Widerspruchsrecht nur bei Vorliegen von Gründen, die sich aus Ihrer besonderen Situation ergeben, zu.</p> <p>Nach Ausübung Ihres Widerspruchsrechts werden wir Ihre personenbezogenen Daten nicht weiter zu diesen Zwecken verarbeiten, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten überwiegen, oder wenn die Verarbeitung der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen dient.</p> <p>Dies gilt nicht, wenn die Verarbeitung zu Zwecken des Direktmarketings erfolgt. Dann werden wir Ihre personenbezogenen Daten nicht weiter zu diesem Zweck verarbeiten.</p> </td> </tr> </tbody> </table> 
          <h3>7.2 Kontaktmöglichkeiten</h3>
           <p>Bei Fragen zur Erhebung, Verarbeitung oder Nutzung Ihrer personenbezogenen Daten, bei Auskünften, Berichtigung, Einschränkung oder Löschung von Daten sowie Widerruf erteilter Einwilligungen oder Widerspruch gegen eine bestimmte Datenverwendung wenden Sie sich bitte direkt an uns über die Kontaktdaten in unserem Impressum.</p> 
          <p>
  
      <a href="https://legal.trustedshops.com/produkte/rechtstexter" target="_blank">Datenschutzerklärung</a>
      erstellt mit dem
      <a href="https://legal.trustedshops.com" target="_blank">Trusted Shops</a>
                  Rechtstexter
          </p>

          <a href="https://legal.trustedshops.com" rel="noopener"> <img src="https://legal-images.trustedshops.com/Rechtspartner-Logo.png" alt="Rechtspartner-Logo" width="268" loading="lazy" /> </a>


      <p>

      Unser Unternehmen prüft regelmäßig bei Vertragsabschlüssen und in bestimmten Fällen, in denen
ein berechtigtes Interesse vorliegt auch bei Bestandskunden Ihre Bonität. Dazu arbeiten wir mit der
Creditreform Boniversum GmbH, Hammfelddamm 13, 41460 Neuss zusammen, von der wir die dazu
benötigten Daten erhalten. Im Auftrage von Creditreform Boniversum teilen wir Ihnen bereits vorab
dazu folgende Informationen gem. Art. 14 EU-DSGVO mit:
Die Creditreform Boniversum GmbH ist eine Konsumentenauskunftei. Sie betreibt eine Datenbank, in
der Bonitätsinformationen über Privatpersonen gespeichert werden.
Auf dieser Basis erteilt Creditreform Boniversum Bonitätsauskünfte an ihre Kunden. Zu den Kunden
gehören beispielsweise Kreditinstitute, Leasinggesellschaften, Versicherungen,Telekommunikationsunternehmen, Unternehmen des Forderungsmanagements, Versand-, Groß- und Einzelhandelsfirmen
sowie andere Unternehmen, die Waren oder Dienstleistungen liefern bzw. erbringen. Im Rahmen der
gesetzlichen Bestimmungen wird ein Teil der in der Auskunftsdatenbank vorhandenen Daten auch für
die Belieferung anderer Firmendatenbanken, u. a. zur Verwendung für Adress-Handelszwecke genutzt.
In der Datenbank der Creditreform Boniversum werden insbesondere Angaben gespeichert über den
Namen, die Anschrift, das Geburtsdatum, ggf. die E-Mail-Adresse, das Zahlungsverhalten und die
Beteiligungsverhältnisse von Personen. Zweck der Verarbeitung der gespeicherten Daten ist die
Erteilung von Auskünften über die Kreditwürdigkeit der angefragten Person. Rechtsgrundlage für die
Verarbeitung ist Art. 6 Abs. 1f EU-DSGVO. Auskünfte über diese Daten dürfen danach nur erteilt werden,
wenn ein Kunde ein berechtigtes Interesse an der Kenntnis dieser Informationen glaubhaft darlegt.
Sofern Daten in Staaten außerhalb der EU übermittelt werden, erfolgt dies auf Basis der sog.
„Standardvertragsklauseln“, die Sie unter dem Link https://eur-lex.europa.eu/legalcontent/DE/TXT/HTML/?uri=CELEX:32021D0914&from=DE einsehen oder sich von dort zusenden
lassen können.
Die Daten werden solange gespeichert, wie ihre Kenntnis für die Erfüllung des Zwecks der Speicherung
notwendig ist. Notwendig ist die Kenntnis in der Regel für eine Speicherdauer von zunächst drei Jahren.
Nach Ablauf wird geprüft, ob eine Speicherung weiterhin notwendig ist, andernfalls werden die Daten
taggenau gelöscht. Im Falle der Erledigung eines Sachverhalts werden die Daten drei Jahre nach
Erledigung taggenau gelöscht. Eintragungen im Schuldnerverzeichnis werden gemäß § 882e ZPO nach
Ablauf von drei Jahren seit dem Tag der Eintragungsanordnung taggenau gelöscht. Weitere
Informationen finden Sie dazu auch unter www.boniversum.de/bonipedia/ unter der Rubrik
Datenlöschung.
Berechtigte Interessen im Sinne des Art. 6 Abs. 1f EU-DSGVO können sein: Kreditentscheidung,
Geschäftsanbahnung, Beteiligungsverhältnisse, Forderung, Bonitätsprüfung, Versicherungsvertrag,
Vollstreckungsauskunft.
Sie haben gegenüber der Creditreform Boniversum GmbH ein Recht auf Auskunft über die dort zu Ihrer
Person gespeicherten Daten. Soweit die über Sie gespeicherten Daten falsch sein sollten, haben Sie
einen Anspruch auf Berichtigung oder Löschung. Kann nicht sofort festgestellt werden, ob die Daten falsch oder richtig sind, haben Sie bis zur Klärung einen Anspruch auf Sperrung der jeweiligen Daten.
Sind Ihre Daten unvollständig, so können Sie deren Vervollständigung verlangen.
Sofern Sie Ihre Einwilligung zur Verarbeitung der bei Creditreform Boniversum gespeicherten Daten
gegeben haben, haben Sie das Recht, diese Einwilligung jederzeit zu widerrufen. Durch den Widerruf
wird die Rechtmäßigkeit der aufgrund Ihrer Einwilligung bis zu einem etwaigen Widerruf erfolgten
Verarbeitung Ihrer Daten nicht berührt.
Sollten Sie Einwände, Wünsche oder Beschwerden zum Datenschutz haben, können Sie sich mit den
unten aufgeführten Kontaktdaten jederzeit an den Datenschutzbeauftragten der Creditreform
Boniversum wenden. Dieser wird Ihnen schnell und vertrauensvoll in allen Fragen des Datenschutzes
weiterhelfen. Im Falle eines vermuteten Datenschutzverstoßes haben Sie das Recht, sich bei einer
Landesdatenschutzaufsichtsbehörde zu beschweren. Zuständig für die Creditreform Boniversum ist
die Landesbeauftragte für Datenschutz NRW, Postfach 20 24 44, 40102 Düsseldorf,
E-Mail: poststelle@ldi.nrw.de.
Die Daten, die Creditreform Boniversum zu Ihnen gespeichert hat, stammen aus öffentlich
zugänglichen Quellen, von Inkassounternehmen und von deren Kunden. Um Ihre Bonität zu
beschreiben, bildet Creditreform Boniversum zu Ihren Daten einen Scorewert. In den Scorewert fließen
Daten zu Alter und Geschlecht, Adressdaten und teilweise Zahlungserfahrungsdaten ein. Diese Daten
fließen mit unterschiedlicher Gewichtung in die Scorewertberechnung ein. Die Creditreform
Boniversum-Kunden nutzen die Scorewerte als Hilfsmittel bei der Durchführung eigener
Kreditentscheidungen.
Widerspruchsrecht:
Sie können nach Art. 21 Abs. 1 DSGVO der Datenverarbeitung aus Gründen, die sich aus Ihrer
besonderen Situation ergeben (z. B. Frauenhaus oder Zeugenschutz), widersprechen.
Ihren formlosen Widerspruch können Sie schriftlich an die Creditreform Boniversum GmbH,
Hammfelddamm 13, 41460 Neuss oder per E-Mail an selbstauskunft@boniversum.de richten.
Wenn Sie der Verarbeitung Ihrer Daten für Werbe- und Marketingzwecke bei der Boniversum
widersprechen, werden die Daten für diese Zwecke nicht mehr verarbeitet.
Verantwortlich im Sinne des Art. 4 Nr. 7 EU-DSGVO ist die Creditreform Boniversum GmbH,
Hammfelddamm 13, 41460 Neuss. Ihr Ansprechpartner bei der Boniversum ist der Consumer
Service, Tel.: 02131 36845560, Fax: 02131 36845570, E-Mail: selbstauskunft@boniversum.de.
Den zuständigen Datenschutzbeauftragten der Boniversum erreichen Sie unter folgenden
Kontaktdaten: Creditreform Boniversum GmbH, Datenschutzbeauftragter, Hammfelddamm 13,
41460 Neuss, E-Mail: datenschutz@boniversum.de. 
      </p>
    </main>

    <Footer />
    </>
  )
};
 